/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/bangumi/': RouteRecordInfo<'/bangumi/', '/bangumi', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/course-CloudDisk': RouteRecordInfo<'/posts/course-CloudDisk', '/posts/course-CloudDisk', Record<never, never>, Record<never, never>>,
    '/posts/course-Frp': RouteRecordInfo<'/posts/course-Frp', '/posts/course-Frp', Record<never, never>, Record<never, never>>,
    '/posts/course-GPU-TDR': RouteRecordInfo<'/posts/course-GPU-TDR', '/posts/course-GPU-TDR', Record<never, never>, Record<never, never>>,
    '/posts/course-Hexo': RouteRecordInfo<'/posts/course-Hexo', '/posts/course-Hexo', Record<never, never>, Record<never, never>>,
    '/posts/course-Img': RouteRecordInfo<'/posts/course-Img', '/posts/course-Img', Record<never, never>, Record<never, never>>,
    '/posts/course-MCBE-Sever': RouteRecordInfo<'/posts/course-MCBE-Sever', '/posts/course-MCBE-Sever', Record<never, never>, Record<never, never>>,
    '/posts/course-MCBE-Sever-1': RouteRecordInfo<'/posts/course-MCBE-Sever-1', '/posts/course-MCBE-Sever-1', Record<never, never>, Record<never, never>>,
    '/posts/course-MCBE-Sever-2': RouteRecordInfo<'/posts/course-MCBE-Sever-2', '/posts/course-MCBE-Sever-2', Record<never, never>, Record<never, never>>,
    '/posts/course-onecloud-armbian': RouteRecordInfo<'/posts/course-onecloud-armbian', '/posts/course-onecloud-armbian', Record<never, never>, Record<never, never>>,
    '/posts/course-onecloud-LANraragi': RouteRecordInfo<'/posts/course-onecloud-LANraragi', '/posts/course-onecloud-LANraragi', Record<never, never>, Record<never, never>>,
    '/posts/course-OPPO-A83': RouteRecordInfo<'/posts/course-OPPO-A83', '/posts/course-OPPO-A83', Record<never, never>, Record<never, never>>,
    '/posts/course-SM-T311': RouteRecordInfo<'/posts/course-SM-T311', '/posts/course-SM-T311', Record<never, never>, Record<never, never>>,
    '/posts/course-Win10-FAQ': RouteRecordInfo<'/posts/course-Win10-FAQ', '/posts/course-Win10-FAQ', Record<never, never>, Record<never, never>>,
    '/posts/course-Win10-RD': RouteRecordInfo<'/posts/course-Win10-RD', '/posts/course-Win10-RD', Record<never, never>, Record<never, never>>,
    '/posts/log-MCBEServer-Localhost-FAQ': RouteRecordInfo<'/posts/log-MCBEServer-Localhost-FAQ', '/posts/log-MCBEServer-Localhost-FAQ', Record<never, never>, Record<never, never>>,
    '/posts/log-OPPO-A83-ROM': RouteRecordInfo<'/posts/log-OPPO-A83-ROM', '/posts/log-OPPO-A83-ROM', Record<never, never>, Record<never, never>>,
    '/posts/resource-Domain-Tool': RouteRecordInfo<'/posts/resource-Domain-Tool', '/posts/resource-Domain-Tool', Record<never, never>, Record<never, never>>,
    '/posts/resource-Free-Email': RouteRecordInfo<'/posts/resource-Free-Email', '/posts/resource-Free-Email', Record<never, never>, Record<never, never>>,
    '/posts/wiki-Android-Code-Versions': RouteRecordInfo<'/posts/wiki-Android-Code-Versions', '/posts/wiki-Android-Code-Versions', Record<never, never>, Record<never, never>>,
    '/posts/wiki-Android-Mode': RouteRecordInfo<'/posts/wiki-Android-Mode', '/posts/wiki-Android-Mode', Record<never, never>, Record<never, never>>,
    '/posts/wiki-Disk': RouteRecordInfo<'/posts/wiki-Disk', '/posts/wiki-Disk', Record<never, never>, Record<never, never>>,
    '/posts/wiki-DNS-Address': RouteRecordInfo<'/posts/wiki-DNS-Address', '/posts/wiki-DNS-Address', Record<never, never>, Record<never, never>>,
    '/posts/wiki-Screen': RouteRecordInfo<'/posts/wiki-Screen', '/posts/wiki-Screen', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
